### ISSUE TITLE
Include parking and property details (private pool, stories, etc)

### ISSUE THREAD

**Issue by majestique** [cermak-petr/actor-zillow-api-scraper#23]
Requesting these fields to be added in the scrape, thank you!
![image](https://user-images.githubusercontent.com/19336285/110050372-9c465f00-7d08-11eb-83ff-64098f52a8a2.png)

**Comment by zpelechova** [comment]
You can easily ad those with extend output part of the input - the information is not from parsing the web but from json similar to here - so any extra fields you can add:

async ({ item, data }) => {
  item.country = data.country; // add new array data
  return item; // need to return the item here, otherwise your dataset willbe empty
}

In your case e.g.
async ({ item, data }) => {
  item.hasPrivatePool = data.pool; // add new array data
  item.homeType= data.homeType; // add new array data
-> here any other further items you would like to add
  return item; // need to return the item here, otherwise your dataset willbe empty
}
